# sucessfully tested this configuration for restoring from Azure and in-cluster Backup

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: commafeed-postgres-restore
  namespace: commafeed
spec:
  description: "test recovery commafeed db"
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  storage:
    storageClass: local-path
    size: 1Gi

  # use the source: clusterBackup for restoring from Azure blob
  # when restoring from in-cluster Backup object, use backup and backup.name

  bootstrap:
    recovery:
      source: clusterBackup
      # backup:
      #   name: commafeed-scheduled-backup-20240101173000
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-db-creds

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "https://mischahomelabk8sbackups.blob.core.windows.net/commafeed"
        serverName: commafeed-postgres
        azureCredentials:
          storageAccount:
            name: azure-creds
            key: commafeed-storage-account-name
          storageSasToken:
            name: azure-creds
            key: commafeed-blob-sas
