apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: ScheduledBackup
metadata:
  name: commafeed-db-staging
  namespace: commafeed
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: commafeed-db-staging
