---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-default-dashboards
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.0.19"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    adminPassword: strongpassword

    # You can override these with env variables! https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/

    grafana.ini:
      date_formats:
        default_week_start: monday
      security:
        allow_embedding: true

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - hosts:
            - grafana.mischavandenburg.net
          secretName: grafana-ingress-prod
      hosts:
        - grafana.mischavandenburg.net

    persistence:
      enabled: true
      type: pvc
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      size: 4Gi

    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        # Allow discovery in all namespaces for dashboards
        searchNamespace: ALL

        ## Annotations for Grafana dashboard configmaps
        ##
        annotations: {}
        multicluster:
          global:
            enabled: false
          etcd:
            enabled: false
        provider:
          allowUiUpdates: false

    # configuration to load default dashboards from persistent volume
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            updateIntervalSeconds: 10 # how often Grafana will scan for changed dashboards
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/default
              foldersFromFilesStructure: false
    extraVolumeMounts:
      - name: grafana-default-dashboards
        mountPath: /var/lib/grafana/dashboards/default
    extraVolumes:
      - name: grafana-default-dashboards
        existingClaim: grafana-default-dashboards
