apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - database.yaml
  - scheduled-backup.yaml
  - ../../base/linkding/
  - cloudflare.yaml
  # - backup-restore-linkding.yaml

patches:
  - target:
      kind: SecretProviderClass
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: k8s-homelab-production
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-production
      - op: replace
        path: /spec/tls/0/secretName
        value: linkding-ingress-production
