apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
        try: "0"
    spec:
      # securityContext:
      #   runAsUser: 3000
      #   runAsGroup: 3000
      #   fsGroup: 3000

      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:0.14.5

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: homarr-configmap

          ports:
            - containerPort: 7575
              protocol: TCP

          volumeMounts:
            - name: homarr-config
              mountPath: "/app/data/configs"
            - name: homarr-database
              mountPath: "/app/database"
            - name: homarr-icons
              mountPath: "/app/public/icons"

      restartPolicy: Always

      volumes:
        - name: homarr-config
          persistentVolumeClaim:
            claimName: homarr-config
        - name: homarr-database
          persistentVolumeClaim:
            claimName: homarr-database
        - name: homarr-icons
          persistentVolumeClaim:
            claimName: homarr-icons
