---
apiVersion: v1
kind: Namespace
metadata:
  name: homarr
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 24h
  url: https://oben01.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: "1.0.4"
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: homarr
      interval: 12h
  values:
    persistence:
      enabled: true

    ingress:
      enabled: true
      className: traefik
    hosts:
      - host: home.mischavandenburg.net
        paths:
          - path: /
            pathType: Prefix
    # tls:
    #   - hosts:
    #     - "homarr.homelab.dev"
    #     - "www.homarr.homelab.dev"
    #     secretName: homelab-tls
