apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
        policy-type: "app"
    spec:
      containers:
        - name: health-api
          image: ghcr.io/mischavandenburg/health-api:v0.2.0
          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: health-api-configmap
            - secretRef:
                name: health-api-container-env

          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true

      restartPolicy: Always

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-secrets-health
            nodePublishSecretRef: # Only required when using service principal mode
              name: secrets-store-creds # Only required when using service principal mode
