apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets-health
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s

    objects: |
      array:
        - |
          objectName: health-connection-string
          objectType: secret
        - |
          objectName: health-storage-account-name
          objectType: secret
        - |
          objectName: health-blob-sas
          objectType: secret
        - |
          objectName: health-db-username
          objectType: secret
        - |
          objectName: health-db-password
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: health-connection-string
          objectName: health-connection-string
        - key: health-storage-account-name
          objectName: health-storage-account-name
        - key: health-blob-sas
          objectName: health-blob-sas
      secretName: azure-creds
      type: Opaque

    - data:
        - key: username
          objectName: health-db-username
        - key: password
          objectName: health-db-password
      secretName: health-db-creds
      type: kubernetes.io/basic-auth

    - data:
        - key: DB_USER
          objectName: health-db-username
        - key: DB_PASSWORD
          objectName: health-db-password

      secretName: health-api-container-env
      type: Opaque
