---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: edb
  namespace: postgresql-operator-system
spec:
  interval: 24h
  url: https://enterprisedb.github.io/edb-postgres-for-kubernetes-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: edb-postgres-for-kubernetes
  namespace: postgresql-operator-system
spec:
  interval: 30m
  chart:
    spec:
      chart: edb-postgres-for-kubernetes
      version: "0.20.0"
      sourceRef:
        kind: HelmRepository
        name: edb
        namespace: postgresql-operator-system
      interval: 12h
  # values:
