apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: skool-db-production-v1
spec:
  backup:
    barmanObjectStore:
      azureCredentials:
        storageAccount:
          key: skool-storage-account-name
          name: azure-creds
        storageSasToken:
          key: skool-blob-sas
          name: azure-creds
      data:
        compression: gzip
      destinationPath: https://hldatabaseproduction.blob.core.windows.net/skool
      wal:
        compression: gzip
    retentionPolicy: 14d

  bootstrap:
    recovery:
      source: clusterBackup
      database: skool
      owner: skool
      secret:
        name: skool-db-creds


  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "https://hldatabaseproduction.blob.core.windows.net/skool"
        serverName: skool-db-production-v0
        azureCredentials:
          storageAccount:
            name: azure-creds
            key: skool-storage-account-name
          storageSasToken:
            name: azure-creds
            key: skool-blob-sas


  description: Postgres cluster for the skool application
  imageName: quay.io/enterprisedb/postgresql:16.1
  inheritedMetadata:
    labels:
      app: skool-database
      policy-type: database
  instances: 3
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: 100Mi
  storage:
    size: 1Gi
