---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: mealie-db
  namespace: mealie
spec:
  description: Postgres cluster for the Mealie application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  bootstrap:
    initdb:
      database: mealie
      owner: mealie
      secret:
        name: mealie-db-creds

  storage:
    storageClass: local-path
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: "https://mischahomelabk8sbackups.blob.core.windows.net/mealie"
      azureCredentials:
        storageAccount:
          name: azure-creds
          key: mealie-storage-account-name
        storageSasToken:
          name: azure-creds
          key: mealie-blob-sas
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  # handy: resources can be used to trigger a redeploy
  resources:
    requests:
      memory: 300Mi
  #     cpu: "1"
  # limits:
  #   memory: "1Gi"
  #   cpu: "2"

  # affinity:
  #   enablePodAntiAffinity: true
  #   topologyKey: failure-domain.beta.kubernetes.io/zone
---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: ScheduledBackup
metadata:
  name: mealie-scheduled-backup
  namespace: mealie
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: mealie-postgres
