apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: mealie
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s # the name of the KeyVault

    objects: |
      array:
        - |
          objectName: mealie-connection-string
          objectType: secret
        - |
          objectName: mealie-storage-account-name
          objectType: secret
        - |
          objectName: mealie-blob-sas
          objectType: secret
        - |
          objectName: mealie-db-username
          objectType: secret
        - |
          objectName: mealie-db-password
          objectType: secret
        - |
          objectName: mealie-db-host
          objectType: secret
    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects: # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
    - data:
        - key: mealie-connection-string # data field to populate
          objectName: mealie-connection-string # name of the mounted content to sync; this could be the object name or the object alias
        - key: mealie-storage-account-name # data field to populate
          objectName: mealie-storage-account-name # name of the mounted content to sync; this could be the object name or the object alias
        - key: mealie-blob-sas # data field to populate
          objectName: mealie-blob-sas # name of the mounted content to sync; this could be the object name or the object alias
      secretName: azure-creds # name of the Kubernetes secret object
      type: Opaque # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
    - data:
        - key: username
          objectName: mealie-db-username
        - key: password
          objectName: mealie-db-password
        - key: host
          objectName: mealie-db-host
      secretName: mealie-db-creds
      type: kubernetes.io/basic-auth
    - data:
        - key: POSTGRES_SERVER
          objectName: mealie-db-host
        - key: POSTGRES_USER
          objectName: mealie-db-username
        - key: POSTGRES_PASSWORD
          objectName: mealie-db-password

      secretName: mealie-container-env
      type: Opaque
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-cloudflare
  namespace: mealie
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s
    objects: |
      array:
        - |
          objectName: mealie-cloudflare-tunnel
          objectType: secret
    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
