apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: mealie-data
  namespace: mealie
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
