# sucessfully tested this configuration for restoring from Azure and in-cluster Backup

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: mealie-postgres-restore
  namespace: mealie
spec:
  description: "test recovery mealie db"
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  storage:
    storageClass: local-path
    size: 1Gi

  # use the source: clusterBackup for restoring from Azure blob
  # when restoring from in-cluster Backup object, use backup and backup.name

  bootstrap:
    recovery:
      source: clusterBackup
      # backup:
      #   name: mealie-scheduled-backup-20240101173000
      database: mealie
      owner: mealie
      secret:
        name: mealie-db-creds

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "https://mischahomelabk8sbackups.blob.core.windows.net/mealie"
        serverName: mealie-postgres
        azureCredentials:
          storageAccount:
            name: azure-creds
            key: mealie-storage-account-name
          storageSasToken:
            name: azure-creds
            key: mealie-blob-sas
