apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-cloudflare
  namespace: calibre
spec:
  provider: azure
  parameters:
    keyvaultName: k8s-homelab-production
    objects: |
      array:
        - |
          objectName: calibre-cloudflare-tunnel
          objectType: secret
    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
