apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s

    objects: |
      array:
        - |
          objectName: n8n-connection-string
          objectType: secret
        - |
          objectName: n8n-storage-account-name
          objectType: secret
        - |
          objectName: n8n-blob-sas
          objectType: secret
        - |
          objectName: n8n-db-username
          objectType: secret
        - |
          objectName: n8n-db-password
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: n8n-connection-string
          objectName: n8n-connection-string
        - key: n8n-storage-account-name
          objectName: n8n-storage-account-name
        - key: n8n-blob-sas
          objectName: n8n-blob-sas
      secretName: azure-creds
      type: Opaque

    - data:
        - key: username
          objectName: n8n-db-user
        - key: password
          objectName: n8n-db-password
      secretName: n8n-db-creds
      type: kubernetes.io/basic-auth

    - data:
        - key: DB_POSTGRESDB_USER
          objectName: n8n-db-username
        - key: DB_POSTGRESDB_PASSWORD
          objectName: n8n-db-password
      secretName: n8n-container-env
      type: Opaque
# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-kv-cloudflare
#   namespace: n8n
# spec:
#   provider: azure
#   parameters:
#     keyvaultName: mischa-homelab-k8s
#     objects: |
#       array:
#         - |
#           objectName: n8n-cloudflare-tunnel
#           objectType: secret
#     tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
