apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - ../../base/commafeed/
  # - database.yaml
  # - scheduled-backup.yaml
  - cloudflare.yaml
  - networkpolicy.yaml

patches:
  - target:
      kind: SecretProviderClass
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: k8s-homelab-production
