---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: zettelkasten-tracker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zettelkasten-tracker
  policy:
    semver:
      range: ">=0.0.0 <1.0.0"
