apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: ScheduledBackup
metadata:
  name: health-db-production
  namespace: health
spec:
  backupOwnerReference: cluster
  cluster:
    name: health-db-production-v0
  immediate: true
  schedule: 0 0 4 * *
