apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "5.41.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: "filesystem"
    singleBinary:
      replicas: 1
      persistence:
        storageClass: local-path
    # write:
    #   persistence:
    #     storageClass: local-path
    # read:
    #   persistence:
    #     storageClass: local-path
    # backend:
    #   persistence:
    #     storageClass: local-path
