apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: ScheduledBackup
metadata:
  name: mealie-scheduled-backup
  namespace: mealie
spec:
  immediate: true
  schedule: "0 */15 * * * *"
  backupOwnerReference: cluster
  cluster:
    name: mealie-postgres
