---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: mealie-postgres
  namespace: mealie
spec:
  description: "Postgres cluster for the Mealie application"
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  bootstrap:
    initdb:
      database: mealie
      owner: mealie
      secret:
        name: mealie-db-creds

  storage:
    storageClass: local-path
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: "https://mischahomelabk8sbackups.blob.core.windows.net/mealie"
      azureCredentials:
        connectionString:
          name: azure-creds
          key: mealie-connection-string
        storageAccount:
          name: azure-creds
          key: mealie-storage-account-name
        # storageKey:
        #   name: azure-creds
        #   key: AZURE_STORAGE_KEY
        storageSasToken:
          name: azure-creds
          key: mealie-blob-sas
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"

  # resources:
  #   requests:
  #     memory: "512Mi"
  #     cpu: "1"
  # limits:
  #   memory: "1Gi"
  #   cpu: "2"

  # affinity:
  #   enablePodAntiAffinity: true
  #   topologyKey: failure-domain.beta.kubernetes.io/zone

  # nodeMaintenanceWindow:
  #   inProgress: false
  #   reusePVC: false
