apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - ../../base/homarr-new/
  - ingress.yaml
# patches:
#   - target:
#       kind: Ingress
#     patch: |-
#       - op: replace
#         path: /metadata/annotations/cert-manager.io~1cluster-issuer
#         value: letsencrypt-production
#       - op: replace
#         path: /spec/tls/0/secretName
#         value: homarr-ingress-production
