---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.0.19"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    adminPassword: strongpassword
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - hosts:
            - grafana.mischavandenburg.net
          secretName: grafana-ingress-prod
      hosts:
        - grafana.mischavandenburg.net
    persistence:
      enabled: true
      type: pvc
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      size: 4Gi
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            updateIntervalSeconds: 10 # how often Grafana will scan for changed dashboards
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/default
              foldersFromFilesStructure: false
    extraVolumeMounts:
      # This will implicitly create an `emptyDir` volume as well (quite surprising),
      # so we do not require the value `extraContainerVolumes`.
      - name: collection
        mountPath: /var/lib/grafana/dashboards/default
    extraVolumes:
      - name: collection
        emptyDir:
          sizeLimit: 500Mi
