---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: "0.7.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  # values:
  #   adminPassword: strongpassword
  #   ingress:
  #     enabled: true
  #     ingressClassName: traefik
  #     annotations:
  #       cert-manager.io/cluster-issuer: letsencrypt-prod
  #     tls:
  #       - hosts:
  #           - grafana.mischavandenburg.net
  #         secretName: grafana-ingress-prod
  #     hosts:
  #       - grafana.mischavandenburg.net
  #     persistence:
  #       enabled: true
  #       type: pvc
  #       storageClassName: local-path
  #       accessModes:
  #         - ReadWriteOnce
  #       size: 4Gi
