---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: "0.7.3"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    cluster:
      name: homelab
    logs:
      enabled: false
    prometheus-operator-crds:
      enabled: false
    externalServices:
      prometheus:
        host: prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091
        # basicAuth:
        #   username: promdata
        #   password: promdata
