---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-secrets-store-provider-azure
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-secrets-store-provider-azure
  namespace: csi-secrets-store-provider-azure
spec:
  interval: 24h
  url: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-secrets-store-provider-azure
  namespace: csi-secrets-store-provider-azure
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      version: "1.5.0"
      sourceRef:
        kind: HelmRepository
        name: csi-secrets-store-provider-azure
        namespace: csi-secrets-store-provider-azure
      interval: 12h
