apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-default-dashboards
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
  volumeMode: Filesystem
