apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: n8n-db-production-v0
  namespace: n8n
spec:
  backup:
    barmanObjectStore:
      azureCredentials:
        storageAccount:
          key: n8n-storage-account-name
          name: azure-creds
        storageSasToken:
          key: n8n-blob-sas
          name: azure-creds
      data:
        compression: gzip
      destinationPath: https://hldatabaseproduction.blob.core.windows.net/n8n
      wal:
        compression: gzip
    retentionPolicy: 14d
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-creds
  description: Postgres cluster for the n8n application
  imageName: quay.io/enterprisedb/postgresql:16.1
  inheritedMetadata:
    labels:
      app: n8n-database
      policy-type: database
  instances: 3
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: 100Mi
  storage:
    size: 1Gi
