apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-data
  namespace: calibre
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: calibre-books
#   namespace: calibre
# spec:
#   storageClassName: local-path
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
