apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-configmap
  namespace: mealie
data:
  ALLOW_SIGNUP: "false"
  BASE_URL: https://mealie.mischavandenburg.net
  DB_ENGINE: postgres
  POSTGRES_DB: mealie
  POSTGRES_PORT: "5432"
  PUID: "1000"
  PGID: "1000"
  TZ: UTC+1
