apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: mealie-db-production-v1
  namespace: mealie
spec:
  description: Postgres cluster for the Mealie application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: mealie-database
      policy-type: "database"

  bootstrap:
    recovery:
      source: clusterBackup
      database: mealie
      owner: mealie

      secret:
        name: mealie-db-creds

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: https://hldatabaseproduction.blob.core.windows.net/mealie
        serverName: mealie-db-production
        azureCredentials:
          storageAccount:
            name: azure-creds
            key: mealie-storage-account-name
          storageSasToken:
            name: azure-creds
            key: mealie-blob-sas

  storage:
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: https://hldatabaseproduction.blob.core.windows.net/mealie
      azureCredentials:
        storageAccount:
          name: azure-creds
          key: mealie-storage-account-name
        storageSasToken:
          name: azure-creds
          key: mealie-blob-sas
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  # handy: resources can be used to trigger a redeploy
  resources:
    requests:
      memory: 210Mi
      cpu: 250m
