apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mealie/
  # - database.yaml
  - configmap.yaml
  - cloudflare.yaml
  - scheduled-backup.yaml
  - networkpolicy.yaml

patches:
  - target:
      kind: SecretProviderClass
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: k8s-homelab-production
