apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.3.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    # You can override these with env variables! https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
    grafana.ini:
      date_formats:
        default_week_start: monday
      security:
        allow_embedding: true

    adminPassword: strongpassword

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
        - hosts:
            - grafana.mischavandenburg.net
          secretName: grafana-ingress-production
      hosts:
        - grafana.mischavandenburg.net
