apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: monitoring
spec:
  provider: azure
  parameters:
    clientID: "b2ec1e45-10d6-4cb0-a33d-fb4c518bcb43" # [OPTIONAL available for version > 1.1.0] client id of the Azure AD Application or managed identity to use for workload identity
    keyvaultName: "mischa-homelab-k8s" # the name of the KeyVault

    objects: |
      array:
        - |
          objectName: grafana-admin-password
          objectType: secret              # object types: secret, key, or cert

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects: # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
    - data:
        - key: password # data field to populate
          objectName: grafana-admin-password # name of the mounted content to sync; this could be the object name or the object alias
      secretName: grafana-custom-secret # name of the Kubernetes secret object
      type: Opaque # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
  namespace: monitoring
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-1
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: grafana-custom-secret
              key: password
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kv-secrets
