apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Homelab:
      - Home Assistant:
            href: https://ass.mischavandenburg.net
            description: Home Assistant
      - Grafana:
            href: http://grafana.mischavandenburg.net
            description: Grafana

    - Reading:
      - Commafeed:
            href: http://commafeed.mischavandenburg.net
            description: Commafeed
      - Hacker News:
            href: https://news.ycombinator.com/
            description: Hacker News

    - Content Creation:
      - YouTube:
            href: https://youtube.com
            description: YouTube
      - YouTube Studio:
            href: https://studio.youtube.com
            description: YouTube Studio
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
