apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  # kubernetes.yaml: |
  #   mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Homelab:
      - Home Assistant:
            href: https://ass.mischavandenburg.net
            description: Home Assistant
            icon: home-assistant.png
      - Grafana:
            href: http://grafana.mischavandenburg.net
            description: Grafana
            icon: grafana.png
      - Synology:
            href: http://192.168.120.186:5000/
            description: Synology
            icon: synology.png
      - Transmission:
            href: http://192.168.120.186:3001/
            description: Transmission
            icon: transmission.png
    - Reading:
      - Commafeed:
            href: http://commafeed.mischavandenburg.net
            description: Commafeed
            icon: commafeed.png
      - Wallabag:
            href: http://wallabag.mischavandenburg.net
            description: Wallabag
            icon: wallabag.png
      - Hacker News:
            href: https://news.ycombinator.com/
            description: Hacker News
            icon: commafeed.png

    - Content Creation:
      - YouTube:
            href: https://youtube.com
            description: YouTube
            icon: youtube.png
      - YouTube Studio:
            href: https://studio.youtube.com
            description: YouTube Studio
            icon: youtube.png
      - X:
            href: https://x.com
            description: X
            icon: x.png
      - LinkedIn:
            href: https://linkedin.com
            description: LinkedIn
            icon: linkedin.png
      - Substack:
              href: https://mischavandenburg.substack.com
              description: Substack
              icon: substack.png
  widgets.yaml: |
    # - kubernetes:
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    #       label: "cluster"
    #     nodes:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    # - resources:
    #     backend: resources
    #     expanded: true
    #     cpu: true
    #     memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
