apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shelly-db-production-cnpg-v0
  namespace: shelly
spec:
  backup:
    barmanObjectStore:
      azureCredentials:
        storageAccount:
          key: shelly-storage-account-name
          name: azure-creds
        storageSasToken:
          key: shelly-blob-sas
          name: azure-creds
      data:
        compression: gzip
      destinationPath: https://hldatabaseproduction.blob.core.windows.net/shelly
      wal:
        compression: gzip
    retentionPolicy: 14d

  bootstrap:
    recovery:
      source: clusterBackup
      database: shelly
      owner: shelly
      secret:
        name: shelly-db-creds

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: https://hldatabaseproduction.blob.core.windows.net/shelly
        serverName: shelly-db-production-v0
        azureCredentials:
          storageAccount:
            name: azure-creds
            key: shelly-storage-account-name
          storageSasToken:
            name: azure-creds
            key: shelly-blob-sas

  description: Postgres cluster for the shelly application
  imageName: quay.io/enterprisedb/postgresql:16.1
  inheritedMetadata:
    labels:
      app: shelly-database
      policy-type: database
  instances: 3
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: 100Mi
  storage:
    size: 1Gi
