apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: shelly-db-production
  namespace: shelly
spec:
  backupOwnerReference: cluster
  cluster:
    name: shelly-db-production-cnpg-v0
  immediate: true
  schedule: 0 0 4 * *
