apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission

  template:
    metadata:
      labels:
        app: transmission
        try: "0"
        policy-type: "app"

    spec:
      securityContext:
        runAsUser: 1003
        runAsGroup: 1003
        fsGroup: 1003

      containers:
        - name: transmission
          image: haugene/transmission-openvpn

          securityContext:
            allowPrivilegeEscalation: true

          envFrom:
            - configMapRef:
                name: transmission-configmap
            - secretRef:
                name: transmission-container-env

          ports:
            - containerPort: 3004
              protocol: TCP

          volumeMounts:
            - mountPath: /data
              name: transmission-data
            - mountPath: /config
              name: transmission-config
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true

      restartPolicy: Always

      volumes:
        - name: transmission-data
          persistentVolumeClaim:
            claimName: transmission-data
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-config
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-secrets
            nodePublishSecretRef: # Only required when using service principal mode
              name: secrets-store-creds # Only required when using service principal mode
