apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: k8s-homelab-production

    objects: |
      array:
        - |
          objectName: vpn-provider
          objectType: secret
        - |
          objectName: vpn-username
          objectType: secret
        - |
          objectName: vpn-password
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: OPENVPN_PROVIDER
          objectName: vpn-provider
        - key: OPENVPN_USERNAME
          objectName: vpn-username
        - key: OPENVPN_PASSWORD
          objectName: vpn-password

      secretName: transmission-container-env
      type: Opaque
