apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data
spec:
  storageClassName: synology-smb-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: transmission
spec:
  storageClassName: synology-iscsi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
