apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: mealie-db-staging
  namespace: mealie
spec:
  description: Postgres cluster for the Mealie application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  bootstrap:
    initdb:
      database: mealie
      owner: mealie
      secret:
        name: mealie-db-creds

  storage:
    storageClass: local-path
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: "https://hldatabasestaging.blob.core.windows.net/mealie"
      azureCredentials:
        storageAccount:
          name: azure-creds
          key: mealie-storage-account-name
        storageSasToken:
          name: azure-creds
          key: mealie-blob-sas
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 7d

  # handy: resources can be used to trigger a redeploy
  resources:
    requests:
      memory: 300Mi
