apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mealie/
  - database.yaml
  - configmap.yaml
  - ingress.yaml
  - scheduled-backup.yaml
  # - backup-restore-mealie.yaml

patches:
  - target:
      kind: SecretProviderClass
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: k8s-homelab-staging
