apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
spec:
  storageClassName: synology-smb-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
