apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v1
spec:
  # storageClassName: synology-smb-retain
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
