apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
spec:
  storageClassName: synology-iscsi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
