apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s

    objects: |
      array:
        - |
          objectName: zettelkasten-tracker-connection-string
          objectType: secret
        - |
          objectName: zettelkasten-tracker-storage-account-name
          objectType: secret
        - |
          objectName: zettelkasten-tracker-blob-sas
          objectType: secret
        - |
          objectName: zettelkasten-tracker-db-username
          objectType: secret
        - |
          objectName: zettelkasten-tracker-db-password
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: zettelkasten-tracker-connection-string
          objectName: zettelkasten-tracker-connection-string
        - key: zettelkasten-tracker-storage-account-name
          objectName: zettelkasten-tracker-storage-account-name
        - key: zettelkasten-tracker-blob-sas
          objectName: zettelkasten-tracker-blob-sas
      secretName: azure-creds
      type: Opaque

    - data:
        - key: username
          objectName: zettelkasten-tracker-db-username
        - key: password
          objectName: zettelkasten-tracker-db-password
      secretName: zettelkasten-tracker-db-creds
      type: kubernetes.io/basic-auth

    - data:
        - key: DB_USER
          objectName: zettelkasten-tracker-db-username
        - key: DB_PASSWORD
          objectName: zettelkasten-tracker-db-password
      secretName: zettelkasten-tracker-container-env
      type: Opaque
# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-kv-cloudflare
#   namespace: zettelkasten-tracker
# spec:
#   provider: azure
#   parameters:
#     keyvaultName: mischa-homelab-k8s
#     objects: |
#       array:
#         - |
#           objectName: zettelkasten-tracker-cloudflare-tunnel
#           objectType: secret
#     tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
