apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s
    objects: |
      array:
        - |
          objectName: pgadmin-email
          objectType: secret
        - |
          objectName: pgadmin-password
          objectType: secret
    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
  secretObjects:
    - data:
        - key: PGADMIN_DEFAULT_EMAIL
          objectName: pgadmin-email
        - key: PGADMIN_DEFAULT_PASSWORD
          objectName: pgadmin-password
      secretName: pgadmin-container-env
      type: Opaque
