apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s

    objects: |
      array:
        - |
          objectName: linkding-connection-string
          objectType: secret
        - |
          objectName: linkding-storage-account-name
          objectType: secret
        - |
          objectName: linkding-blob-sas
          objectType: secret
        - |
          objectName: linkding-db-username
          objectType: secret
        - |
          objectName: linkding-db-password
          objectType: secret
        - |
          objectName: linkding-db-host
          objectType: secret
        - |
          objectName: linkding-superuser-name
          objectType: secret
        - |
          objectName: linkding-superuser-password
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: linkding-connection-string
          objectName: linkding-connection-string
        - key: linkding-storage-account-name
          objectName: linkding-storage-account-name
        - key: linkding-blob-sas
          objectName: linkding-blob-sas
      secretName: azure-creds
      type: Opaque

    - data:
        - key: username
          objectName: linkding-db-username
        - key: password
          objectName: linkding-db-password
      secretName: linkding-db-creds
      type: kubernetes.io/basic-auth

    - data:
        - key: LD_SUPERUSER_NAME
          objectName: linkding-superuser-name
        - key: LD_SUPERUSER_PASSWORD
          objectName: linkding-superuser-password
        - key: LD_DB_USER
          objectName: linkding-db-username
        - key: LD_DB_PASSWORD
          objectName: linkding-db-password
        - key: LD_DB_HOST
          objectName: linkding-db-host

      secretName: linkding-container-env
      type: Opaque
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-cloudflare
  namespace: linkding
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s
    objects: |
      array:
        - |
          objectName: linkding-cloudflare-tunnel
          objectType: secret
    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
