apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      version: "26.0.0"
  values:
    service:
      externalIPs:
        - 192.168.2.41
