apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shelly
  template:
    metadata:
      labels:
        app: shelly
        policy-type: "app"
    spec:
      containers:
        - name: shelly
          image: ghcr.io/mischavandenburg/shelly:0.0.1

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: shelly-configmap
            - secretRef:
                name: shelly-container-env

          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true

      restartPolicy: Always

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-secrets-shelly
            nodePublishSecretRef: # Only required when using service principal mode
              name: secrets-store-creds # Only required when using service principal mode
