apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: renovate
spec:
  provider: azure
  parameters:
    keyvaultName: k8s-homelab-production

    objects: |
      array:
        - |
          objectName: renovate-token
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: RENOVATE_TOKEN
          objectName: renovate-token

      secretName: renovate-container-env
      type: Opaque
