apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commafeed-data
  namespace: commafeed
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
